url: "http://ameyer.me"
baseurl:

sass:
  sass_dir: public/css
  style: :compressed

plugins:
  - jekyll-archives
  - jekyll-sitemap

jekyll-archives:
  enabled: all
  layouts:
    year: year-archives
    tag: tag-archives
    category: category-archives
    month: month-archives
    day: day-archives
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
